name: Android Kernel CI wadad

on:
  workflow_dispatch:
    inputs:
      KSUNEXT_ENABLED:
        description: 'Enable KernelSU Next integration'
        required: false
        default: false
        type: boolean
      SUSFS_ENABLED:
        description: 'Enable SUSFS integration'
        required: false
        default: false
        type: boolean
      ANDROID_VERSION:
        description: 'Android version (e.g., 13, 14)'
        required: false
        default: 'android13'
        type: string
      KERNEL_VERSION:
        description: 'Kernel version (e.g., 5.10, 5.15)'
        required: false
        default: '5.10'
        type: string

env:
  TOOLCHAIN_VERSION: "aarch64-linux-android-4.9"
  DEFCONFIG: "oneplus/mt6983_v_15.0.0_nord_3_defconfig"
  MAKE_FLAGS: "-j$(nproc --all)"
  ARTIFACT_NAME: "kernel-$(date +'%Y%m%d-%H%M%S')"
  KERNEL_REPO: "https://github.com/OnePlusOSS/android_kernel_5.10_oneplus_mt6983.git"
  KERNEL_BRANCH: "oneplus/mt6983_v_15.0.0_nord_3"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 150
    
    steps:
    - name: Configure Git to use symlinks
      run: | 
         git config --global core.symlinks true
         git config --global protocol.file.allow always
    - uses: actions/checkout@v4
      with:
        sparse-checkout: none  # This preserves symlinks
        fetch-depth: 0
      
    - name: Set up build environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
          x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev \
          libxml2-utils xsltproc unzip fontconfig python3 bc cpio rsync \
          ccache libssl-dev patch

    - name: Clone kernel source
      run: |
        git clone --depth=1 \
          --branch ${{ env.KERNEL_BRANCH }} \
          ${{ env.KERNEL_REPO }} \
          kernel_source
    
    - name: Clone and merge OnePlus modules
      run: |
        # Clone modules to temp dir
        git clone --depth=1 \
          https://github.com/OnePlusOSS/android_kernel_modules_oneplus_mt6983.git \
          -b oneplus/mt6983_v_15.0.0_nord_3 \
          tmp_modules
    
        # Move contents selectively (excluding .git and handling conflicts)
        cd tmp_modules
        find . -maxdepth 1 ! -name .git ! -name . -exec sh -c '
          for item do
            if [ -e "../kernel_source/${item}" ]; then
              if [ -d "${item}" ]; then
                # Merge directories
                cp -r "${item}/"* "../kernel_source/${item}/"
              else
                # Overwrite files
                cp -f "${item}" "../kernel_source/${item}"
              fi
            else
              # Move new items
              mv "${item}" "../kernel_source/"
            fi
          done
        ' sh {} +
        cd ..
        rm -rf tmp_modules
        cd kernel_source
        ls -a
    - name: Debug merged vendor structure
      run: |
        echo "--- Listing kernel_source root after merge ---"
        ls -la /home/runner/work/KSU-NEXT-SUSFS-NORD-3/KSU-NEXT-SUSFS-NORD-3/kernel_source || echo "kernel_source not found"
        echo "--- Listing kernel_source/vendor structure after merge (recursive) ---"
        ls -lR /home/runner/work/KSU-NEXT-SUSFS-NORD-3/KSU-NEXT-SUSFS-NORD-3/kernel_source/vendor || echo "kernel_source/vendor not found"
        echo "--- Specifically checking for vendor/oplus/sensor ---"
        ls -ld /home/runner/work/KSU-NEXT-SUSFS-NORD-3/KSU-NEXT-SUSFS-NORD-3/kernel_source/vendor/oplus/sensor || echo "kernel_source/vendor/oplus/sensor not found"
        echo "--- Specifically checking for sensorhub path ---"
        ls -ld /home/runner/work/KSU-NEXT-SUSFS-NORD-3/KSU-NEXT-SUSFS-NORD-3/kernel_source/vendor/oplus/sensor/kernel/sensorhub/oplus_sensor_devinfo || echo "Specific sensorhub path in kernel_source/vendor NOT found"
      shell: bash

    - name: Repair kernel source symlinks
      working-directory: kernel_source
      run: |
        # Find all broken symlinks and recreate them
        find . -type l ! -exec test -e {} \; -print | while read -r broken_symlink; do
          target=$(readlink "$broken_symlink")
          # Optional: Add a check here if the target *actually* exists now
          # if [ -e "$(dirname "$broken_symlink")/$target" ]; then # Basic relative path check
              echo "Fixing $broken_symlink -> $target"
              rm "$broken_symlink"
              ln -s "$target" "$broken_symlink"
          # else
          #    echo "Skipping $broken_symlink -> $target (Target still missing)"
          # fi
        done
    - name: Automatically fix vendor symlinks based on placeholder files AND add specific fixes
      run: |
        #!/usr/bin/env bash
        # set -e # Temporarily disable exit on error for the potentially buggy auto part

        echo "Starting automated symlink fix based on placeholder files..."
        # Ensure we are in the kernel source directory
        cd /home/runner/work/KSU-NEXT-SUSFS-NORD-3/KSU-NEXT-SUSFS-NORD-3/kernel_source || exit 1
        echo "Current directory: $(pwd)"

        # --- Automated Fix Logic (Potentially Buggy - may still show warnings) ---
        find . \( -path './drivers' -o -path './kernel' -o -path './mm' -o -path './fs' -o -path './sound' \) -prune \
             -o -type f -print0 | \
        while IFS= read -r -d $'\0' placeholder_file; do
          placeholder_content=$(head -n 1 "$placeholder_file" 2>/dev/null || true) # Read first line
          if [[ "$placeholder_content" == ../* ]]; then
            target_path="$placeholder_content"
            abs_placeholder_dir=$(realpath "$(dirname "$placeholder_file")" 2>/dev/null || true) # Suppress realpath errors potentially
            if [ -z "$abs_placeholder_dir" ]; then # If realpath failed
                echo "Warning: realpath failed for dirname of $placeholder_file, skipping automated fix."
                continue
            fi
            abs_target_dir=$(realpath -m "$abs_placeholder_dir/$target_path" 2>/dev/null || true) # Suppress realpath errors potentially
            if [ -z "$abs_target_dir" ]; then # If realpath failed
                echo "Warning: realpath failed for target of $placeholder_file, skipping automated fix."
                continue
            fi

            if [ -d "$abs_target_dir" ]; then
              if [ -f "$abs_target_dir/Kconfig" ]; then
                 echo "Fixing (Auto): '$placeholder_file' -> '$target_path'"
                 mkdir -p "$(dirname "$placeholder_file")"
                 rm -f "$placeholder_file"
                 ln -svf "$target_path" "$placeholder_file"
              else
                 echo "WARNING (Auto): Target '$abs_target_dir' exists, but Kconfig missing. Skipping '$placeholder_file'."
              fi
            else
              echo "INFO (Auto): Placeholder '$placeholder_file' points to non-existent target '$abs_target_dir'. Skipping."
            fi
          fi
        done || echo "Warning: Automated symlink processing encountered errors or warnings." # Allow script to continue even if find/while fails
        echo "Finished automated symlink fix attempt."
        # --- End Automated Fix Logic ---

        # Re-enable exit on error for manual fixes
        set -e

        # --- Add Specific Manual Fixes ---
        echo "Applying specific manual symlink fixes..."

        # Fix for kernel/oplus_cpu  <--- THIS IS NOW ACTIVE ---
        LINK_PATH_CPU="kernel/oplus_cpu"
        # Assuming target is vendor/oplus/kernel/cpu based on initial errors
        TARGET_PATH_CPU="../vendor/oplus/kernel/cpu"
        ABS_TARGET_DIR_CPU="${PWD}/vendor/oplus/kernel/cpu"
        KCONFIG_SUBPATH_CPU="sched/Kconfig" # Specific Kconfig needed

        echo "Checking specific fix for $LINK_PATH_CPU -> $TARGET_PATH_CPU"
        # Check if target exists and has the specific Kconfig
        if [ -d "$ABS_TARGET_DIR_CPU" ] && [ -f "$ABS_TARGET_DIR_CPU/$KCONFIG_SUBPATH_CPU" ]; then
            # Check if link doesn't exist or is not a symlink
            if [ ! -L "$LINK_PATH_CPU" ]; then # Use -L to specifically check for a symlink
                echo "Creating/Fixing link $LINK_PATH_CPU -> $TARGET_PATH_CPU"
                mkdir -p "$(dirname "$LINK_PATH_CPU")"
                # Remove if it exists but isn't a symlink
                if [ -e "$LINK_PATH_CPU" ]; then
                    rm -rf "$LINK_PATH_CPU"
                fi
                ln -svf "$TARGET_PATH_CPU" "$LINK_PATH_CPU"
                ls -ld "$LINK_PATH_CPU" # Verify link
                ls -l "$LINK_PATH_CPU/$KCONFIG_SUBPATH_CPU" || echo "ERROR: Could not find Kconfig via new link!"
            else
                echo "$LINK_PATH_CPU symlink already exists and seems correct. Verifying target..."
                ls -ld "$LINK_PATH_CPU" # Show existing link
                ls -l "$LINK_PATH_CPU/$KCONFIG_SUBPATH_CPU" || echo "ERROR: Kconfig missing via existing link!"
            fi
        else
            echo "WARNING: Target directory '$ABS_TARGET_DIR_CPU' or '$KCONFIG_SUBPATH_CPU' missing for $LINK_PATH_CPU. Cannot create link."
            ls -ld "$ABS_TARGET_DIR_CPU" || true # Show target status
        fi
        echo "-------------------------------------"

        # Add other manual fixes here if the automated part remains unreliable for them

        echo "Finished specific manual symlink fixes."

      shell: bash
    - name: Set up ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ env.TOOLCHAIN_VERSION }}-${{ hashFiles('kernel_source/**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ env.TOOLCHAIN_VERSION }}-

    - name: Check for toolchain cache
      uses: actions/cache@v3
      id: toolchain-cache
      with:
        path: toolchain/${{ env.TOOLCHAIN_VERSION }}
        key: ${{ runner.os }}-toolchain-${{ env.TOOLCHAIN_VERSION }}-${{ hashFiles('kernel_source/**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-toolchain-${{ env.TOOLCHAIN_VERSION }}-
          
    - name: Download toolchain
      if: steps.toolchain-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p toolchain
        cd toolchain
        # Use prebuilt toolchain from ARM instead
        wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz
        tar xf gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz
        mv gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu aarch64-linux-android-4.9
        cd aarch64-linux-android-4.9
        # Verify compiler
        if [ -f "bin/aarch64-none-linux-gnu-gcc" ]; then
          echo "Compiler found at $(pwd)/bin/aarch64-none-linux-gnu-gcc"
          # Create symlinks for expected names
          ln -s aarch64-none-linux-gnu-gcc bin/aarch64-linux-android-gcc
          ln -s aarch64-none-linux-gnu-g++ bin/aarch64-linux-android-g++
        else
          echo "ERROR: Compiler not found!"
          find . -name "*gcc*"
          exit 1
        fi

    - name: Set up KernelSU Next
      if: ${{ inputs.KSUNEXT_ENABLED }}
      working-directory: kernel_source
      run: |
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-dev
        cd KernelSU-Next
        KSU_VERSION=$(expr $(git rev-list --count HEAD) "+" 10200)
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
        cd ..

    - name: Set up SUSFS
      if: ${{ inputs.SUSFS_ENABLED }}
      working-directory: kernel_source
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
        git clone https://github.com/cabagekiller/kernel_patches.git
        #cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
        cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./
        #cp kernel_patches/KernelSU-Next-Implement-SUSFS-v1.5.5-Universal.patch ./KernelSU-Next/
        cp susfs4ksu/kernel_patches/fs/* ./fs/
        cp susfs4ksu/kernel_patches/include/linux/* ./include/linux/
        
        # Apply patches
        cd ./KernelSU-Next
        #patch -p1 < KernelSU-Next-Implement-SUSFS-v1.5.5-Universal.patch || true
        #patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
        cd ..
        patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
        cp kernel_patches/69_hide_stuff.patch ./
        cp kernel_patches/next/syscall_hooks.patch ./
        patch -p1 -F 3 < 69_hide_stuff.patch || true
        patch -p1 -F 3 < syscall_hooks.patch || true
        git add -A && git commit -a -m "BUILD Kernel: Added SUSFS patches" || true
        git add -A && git commit -a -m "BUILD Kernel: SUSFS changes" || true

    - name: Configure Kernel Defconfig
      if: ${{ inputs.KSUNEXT_ENABLED || inputs.SUSFS_ENABLED }}
      working-directory: kernel_source
      run: |
        # Basic KernelSU and SUSFS configs
        echo "CONFIG_KSU=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_WITH_KPROBES=n" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_COMPAT=y" >> ./arch/arm64/configs/gki_defconfig
        # Add additional tmpfs config setting
        echo "CONFIG_TMPFS_XATTR=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./arch/arm64/configs/gki_defconfig
        # Add additional tmpfs config setting
        echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./arch/arm64/configs/gki_defconfig
        echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./arch/arm64/configs/gki_defconfig
        
        # Remove defconfig check if SUSFS is enabled
        if ${{ inputs.SUSFS_ENABLED }}; then
          sed -i '2s/check_defconfig//' ./build.config.gki || true
        fi


    - name: Set up build environment variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=$(pwd)/toolchain/${{ env.TOOLCHAIN_VERSION }}/bin/aarch64-none-linux-gnu-" >> $GITHUB_ENV
        echo "PATH=$(pwd)/toolchain/${{ env.TOOLCHAIN_VERSION }}/bin:$PATH" >> $GITHUB_ENV
        echo "CCACHE_DIR=$(pwd)/.ccache" >> $GITHUB_ENV
        echo "USE_CCACHE=1" >> $GITHUB_ENV
        echo "CCACHE_EXEC=/usr/bin/ccache" >> $GITHUB_ENV
        
        # Verify setup
        echo "Compiler path: $(pwd)/toolchain/${{ env.TOOLCHAIN_VERSION }}/bin/aarch64-none-linux-gnu-gcc"
        $(pwd)/toolchain/${{ env.TOOLCHAIN_VERSION }}/bin/aarch64-none-linux-gnu-gcc --version || (echo "Compiler test failed!" && exit 1)
        
    - name: Show environment info
      working-directory: kernel_source
      run: |
        echo "Toolchain path: $(pwd)/toolchain/${{ env.TOOLCHAIN_VERSION }}/bin"
        echo "CCACHE stats:"
        ccache -s
        if [ -n "$KSUVER" ]; then
          echo "KernelSU Next version: $KSUVER"
        fi
        if ${{ inputs.SUSFS_ENABLED }}; then
          echo "SUSFS enabled for Android ${{ github.event.inputs.ANDROID_VERSION }}, Kernel ${{ github.event.inputs.KERNEL_VERSION }}"
          echo "Modified defconfig with SUSFS settings"
        fi
    - name: Make defconfig
      working-directory: kernel_source
      run: |
        # Verify environment
        echo "Current PATH: $PATH"
        echo "CROSS_COMPILE: $CROSS_COMPILE"
        which aarch64-linux-android-gcc
        aarch64-linux-android-gcc --version
        
        # Create output directory and copy config
        mkdir -p out
        cp arch/arm64/configs/gki_defconfig out/.config
        
        # Apply any modifications
        if [ -n "$(grep 'CONFIG_KSU=y' out/.config)" ]; then
          echo "KernelSU config already present"
        else
          echo "Applying KernelSU config"
          echo "CONFIG_KSU=y" >> out/.config
        fi
        
        # Finalize config
        make O=out olddefconfig

    - name: Build kernel
      working-directory: kernel_source
      run: |
        make O=out ${{ env.MAKE_FLAGS }} 2>&1 | tee build.log
        

    - name: Prepare kernel image
      working-directory: kernel_source
      run: |
        mkdir -p kernel_output
        cp out/arch/arm64/boot/Image.gz-dtb kernel_output/Image.gz-dtb
        # Decompress if needed (some devices need uncompressed Image)
        gunzip -kf kernel_output/Image.gz-dtb || true
        mv kernel_output/Image.gz-dtb kernel_output/Image 2>/dev/null || true

    - name: Set up AnyKernel3
      run: |
        git clone https://github.com/TanakaLun/AnyKernel3 --depth=1
        rm -rf ./AnyKernel3/.git
        # Copy kernel image
        cp kernel_output/Image* ./AnyKernel3/
        # Add version info
        echo "kernel.string=KernelSU Next v${KSUVER} ${FEIL}" >> ./AnyKernel3/anykernel.sh
        echo "device.name1=OnePlus Nord 3" >> ./AnyKernel3/anykernel.sh
        # Modify anykernel.sh for our device
        sed -i 's/do.devicecheck=1/do.devicecheck=0/' ./AnyKernel3/anykernel.sh
        sed -i 's/do.modules=1/do.modules=0/' ./AnyKernel3/anykernel.sh

    - name: Package AnyKernel3 zip
      run: |
        cd AnyKernel3
        zip -r9 ../AnyKernel3_KernelSU_Next_${KSUVER}_${FEIL}.zip * -x .git*
        cd ..

    - name: Upload AnyKernel3 zip
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3_KernelSU_Next_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
        path: ./AnyKernel3_KernelSU_Next_*.zip

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          out/arch/arm64/boot/Image.gz-dtb
          out/.config
          build.log
          kernel_output/*

    - name: Upload build log on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-failure-log
        path: build.log
